/**
 * 시드 300종 (SPEC.md 10.5). scripts/seed-species.ts 가 이 목록으로 종 정보를 만든다.
 *
 * 학명은 현재 통용되는 이름으로 쓴다. 옛 이름으로 알려진 종은 앱이 검색으로 찾을 수 있게
 * 생성된 aliases_ko 가 받아 준다. apps/mobile/src/species/seed.ts 의 번들 30종과 철자를 맞춘다.
 * 국명은 한국 화원의 유통명이고, 프롬프트에 참고로 넣어 name_ko 가 엉뚱해지지 않게 한다.
 */

export interface SeedEntry {
  scientificName: string;
  nameKo: string;
}

const entries = (...rows: [string, string][]): SeedEntry[] =>
  rows.map(([scientificName, nameKo]) => ({ scientificName, nameKo }));

/** 열대 관엽 110종 */
export const TROPICAL = entries(
  ['Monstera deliciosa', '몬스테라'],
  ['Monstera adansonii', '몬스테라 아단소니'],
  ['Monstera dubia', '몬스테라 두비아'],
  ['Epipremnum aureum', '스킨답서스'],
  ['Epipremnum pinnatum', '에피프렘넘 피나텀'],
  ['Philodendron hederaceum', '필로덴드론 하트'],
  ['Philodendron bipinnatifidum', '셀렘'],
  ['Philodendron erubescens', '핑크프린세스'],
  ['Philodendron gloriosum', '글로리오섬'],
  ['Philodendron melanochrysum', '멜라노크리섬'],
  ['Ficus elastica', '인도고무나무'],
  ['Ficus lyrata', '떡갈잎고무나무'],
  ['Ficus umbellata', '움벨라타'],
  ['Ficus altissima', '뱅갈고무나무'],
  ['Goeppertia makoyana', '칼라데아 마코야나'],
  ['Goeppertia orbifolia', '칼라데아 오비포리아'],
  ['Goeppertia lancifolia', '칼라데아 란시폴리아'],
  ['Goeppertia ornata', '칼라데아 오나타'],
  ['Goeppertia roseopicta', '칼라데아 로세오픽타'],
  ['Ctenanthe burle-marxii', '크테난테'],
  ['Maranta leuconeura', '마란타'],
  ['Stromanthe sanguinea', '스트로만테'],
  ['Alocasia odora', '알로카시아'],
  ['Alocasia amazonica', '알로카시아 아마조니카'],
  ['Alocasia zebrina', '알로카시아 제브리나'],
  ['Alocasia cuprea', '알로카시아 쿠프레아'],
  ['Colocasia esculenta', '토란'],
  ['Anthurium andraeanum', '안스리움'],
  ['Anthurium clarinervium', '안스리움 클라리너비움'],
  ['Spathiphyllum wallisii', '스파티필럼'],
  ['Aglaonema commutatum', '아글라오네마'],
  ['Aglaonema modestum', '아글라오네마 모데스텀'],
  ['Dieffenbachia seguine', '디펜바키아'],
  ['Syngonium podophyllum', '싱고니움'],
  ['Scindapsus pictus', '스킨답서스 픽투스'],
  ['Rhaphidophora tetrasperma', '라피도포라'],
  ['Zamioculcas zamiifolia', '금전수'],
  ['Dracaena fragrans', '행운목'],
  ['Dracaena marginata', '드라세나 마지나타'],
  ['Dracaena reflexa', '드라세나 송오브인디아'],
  ['Dracaena sanderiana', '개운죽'],
  ['Dracaena deremensis', '드라세나 자넷크레이그'],
  ['Chamaedorea elegans', '테이블야자'],
  ['Chamaedorea seifrizii', '대나무야자'],
  ['Howea forsteriana', '켄차야자'],
  ['Dypsis lutescens', '아레카야자'],
  ['Rhapis excelsa', '관음죽'],
  ['Caryota mitis', '공작야자'],
  ['Platycerium bifurcatum', '박쥐란'],
  ['Nephrolepis exaltata', '보스턴고사리'],
  ['Asplenium nidus', '아스플레니움'],
  ['Adiantum raddianum', '아디안텀'],
  ['Pteris cretica', '봉작고사리'],
  ['Davallia fejeensis', '토끼고사리'],
  ['Hoya carnosa', '호야'],
  ['Hoya kerrii', '하트호야'],
  ['Hoya obovata', '호야 오보바타'],
  ['Hoya pubicalyx', '호야 푸비칼릭스'],
  ['Peperomia obtusifolia', '페페로미아'],
  ['Peperomia argyreia', '수박페페'],
  ['Peperomia caperata', '주름페페'],
  ['Peperomia polybotrya', '레인드롭페페'],
  ['Fittonia albivenis', '피토니아'],
  ['Goeppertia zebrina', '칼라데아 제브리나'],
  ['Begonia maculata', '베고니아 마쿨라타'],
  ['Begonia rex', '렉스베고니아'],
  ['Tradescantia zebrina', '자주달개비'],
  ['Tradescantia fluminensis', '트라데스칸티아'],
  ['Chlorophytum comosum', '접란'],
  ['Schlumbergera truncata', '게발선인장'],
  ['Codiaeum variegatum', '크로톤'],
  ['Cordyline fruticosa', '코르딜리네'],
  ['Pachira aquatica', '파키라'],
  ['Polyscias fruticosa', '폴리시아스'],
  ['Radermachera sinica', '녹보수'],
  ['Strelitzia reginae', '극락조화'],
  ['Strelitzia nicolai', '극락조'],
  ['Musa acuminata', '바나나나무'],
  ['Alpinia zerumbet', '월도'],
  ['Hedychium coronarium', '생강꽃'],
  ['Monstera siltepecana', '몬스테라 실테페카나'],
  ['Cissus rhombifolia', '시서스'],
  ['Cissus discolor', '레드시서스'],
  ['Ceropegia woodii', '하트덩굴'],
  ['Dischidia nummularia', '디시디아'],
  ['Aeschynanthus radicans', '립스틱'],
  ['Columnea gloriosa', '칼럼네아'],
  ['Episcia cupreata', '에피시아'],
  ['Saintpaulia ionantha', '아프리칸바이올렛'],
  ['Streptocarpus rexii', '스트렙토카르푸스'],
  ['Nematanthus gregarius', '금붕어꽃'],
  ['Selaginella kraussiana', '셀라기넬라'],
  ['Soleirolia soleirolii', '베이비티어스'],
  ['Pilea peperomioides', '필레아'],
  ['Pilea cadierei', '알루미늄플랜트'],
  ['Hypoestes phyllostachya', '히포에스테스'],
  ['Aphelandra squarrosa', '아펠란드라'],
  ['Crossandra infundibuliformis', '크로산드라'],
  ['Justicia brandegeeana', '새우풀'],
  ['Ruellia simplex', '루엘리아'],
  ['Clerodendrum thomsoniae', '클레로덴드론'],
  ['Mandevilla sanderi', '만데빌라'],
  ['Allamanda cathartica', '알라만다'],
  ['Plumeria rubra', '플루메리아'],
  ['Ixora coccinea', '익소라'],
  ['Gardenia jasminoides', '치자나무'],
  ['Hibiscus rosa-sinensis', '하와이무궁화'],
  ['Bougainvillea glabra', '부겐빌레아'],
  ['Passiflora caerulea', '시계꽃'],
  ['Stephanotis floribunda', '마다가스카르자스민'],
);

/** 온대 관엽·실내수목 50종 */
export const TEMPERATE = entries(
  ['Ficus benjamina', '벤자민고무나무'],
  ['Ficus microcarpa', '소엽벤자민'],
  ['Olea europaea', '올리브나무'],
  ['Heptapleurum arboricola', '홍콩야자'],
  ['Hedera helix', '아이비'],
  ['Cupressus macrocarpa', '율마'],
  ['Eucalyptus gunnii', '유칼립투스'],
  ['Camellia japonica', '동백나무'],
  ['Nandina domestica', '남천'],
  ['Cycas revoluta', '소철'],
  ['Ardisia crenata', '만냥금'],
  ['Oxalis triangularis', '사랑초'],
  ['Cyclamen persicum', '시클라멘'],
  ['Laurus nobilis', '월계수'],
  ['Citrus limon', '레몬나무'],
  ['Citrus × meyeri', '메이어레몬'],
  ['Punica granatum', '석류나무'],
  ['Osmanthus fragrans', '금목서'],
  ['Michelia figo', '초령목'],
  ['Daphne odora', '서향'],
  ['Buxus microphylla', '회양목'],
  ['Pittosporum tobira', '돈나무'],
  ['Aucuba japonica', '식나무'],
  ['Fatsia japonica', '팔손이'],
  ['Farfugium japonicum', '털머위'],
  ['Aspidistra elatior', '엽란'],
  ['Asparagus setaceus', '아스파라거스'],
  ['Asparagus densiflorus', '아스파라거스 스프렌게리'],
  ['Ruscus hypoglossum', '루스커스'],
  ['Myrtus communis', '은매화'],
  ['Callistemon citrinus', '병솔나무'],
  ['Leptospermum scoparium', '티트리'],
  ['Melaleuca alternifolia', '멜라루카'],
  ['Grevillea robusta', '그레빌레아'],
  ['Acacia dealbata', '미모사아카시아'],
  ['Schinus molle', '페퍼트리'],
  ['Jasminum polyanthum', '자스민'],
  ['Trachelospermum jasminoides', '마삭줄'],
  ['Rhaphiolepis indica', '다정큼나무'],
  ['Viburnum odoratissimum', '아왜나무'],
  ['Euonymus japonicus', '사철나무'],
  ['Ligustrum japonicum', '광나무'],
  ['Ternstroemia gymnanthera', '후피향나무'],
  ['Elaeocarpus sylvestris', '담팔수'],
  ['Cinnamomum camphora', '녹나무'],
  ['Magnolia grandiflora', '태산목'],
  ['Prunus mume', '매화나무'],
  ['Chaenomeles speciosa', '명자나무'],
  ['Hydrangea macrophylla', '수국'],
  ['Rosa chinensis', '장미'],
);

/** 다육·선인장 60종 */
export const SUCCULENT = entries(
  ['Echeveria elegans', '에케베리아'],
  ['Echeveria agavoides', '아가보이데스'],
  ['Echeveria purpusorum', '푸푸소럼'],
  ['Echeveria laui', '라우이'],
  ['Echeveria derenbergii', '데렌베르기'],
  ['Echeveria pulvinata', '홍복륜'],
  ['Echeveria setosa', '청솔로'],
  ['Echeveria runyonii', '런요니'],
  ['Echeveria shaviana', '샤비아나'],
  ['Echeveria lilacina', '라일라시나'],
  ['Haworthiopsis attenuata', '십이지권'],
  ['Haworthiopsis fasciata', '하월시아 파시아타'],
  ['Haworthia cooperi', '옥로'],
  ['Haworthia retusa', '레투사'],
  ['Haworthia cymbiformis', '심비포미스'],
  ['Sedum morganianum', '당인'],
  ['Sedum rubrotinctum', '을녀심'],
  ['Sedum adolphi', '황금세덤'],
  ['Sedum burrito', '부리토'],
  ['Sedum pachyphyllum', 'virgin세덤'],
  ['Dracaena trifasciata', '산세베리아'],
  ['Dracaena angolensis', '스투키'],
  ['Dracaena masoniana', '산세베리아 마소니아나'],
  ['Dracaena bacularis', '산세베리아 바큘라리스'],
  ['Aloe vera', '알로에'],
  ['Aloe aristata', '아리스타타'],
  ['Aloe juvenna', '유베나'],
  ['Agave americana', '용설란'],
  ['Agave victoriae-reginae', '빅토리아여왕'],
  ['Opuntia microdasys', '백도선'],
  ['Mammillaria elongata', '금수구'],
  ['Mammillaria hahniana', '설백환'],
  ['Gymnocalycium mihanovichii', '비모란'],
  ['Echinocactus grusonii', '금호'],
  ['Ferocactus latispinus', '일출환'],
  ['Astrophytum myriostigma', '난봉옥'],
  ['Astrophytum asterias', '투구'],
  ['Cereus repandus', '귀면각'],
  ['Espostoa lanata', '노락'],
  ['Cleistocactus strausii', '백섬주'],
  ['Parodia magnifica', '파로디아'],
  ['Rebutia minuscula', '레부티아'],
  ['Lophophora williamsii', '오우옥'],
  ['Rhipsalis baccifera', '립살리스'],
  ['Rhipsalis cereuscula', '립살리스 케레우스쿨라'],
  ['Kalanchoe blossfeldiana', '칼랑코에'],
  ['Kalanchoe tomentosa', '월토이'],
  ['Kalanchoe daigremontiana', '가지복랑'],
  ['Crassula ovata', '염좌'],
  ['Crassula perforata', '성을녀'],
  ['Crassula muscosa', '녹탑'],
  ['Graptopetalum paraguayense', '석연화'],
  ['Pachyphytum oviferum', '성미인'],
  ['Senecio rowleyanus', '녹영'],
  ['Curio radicans', '바나나선인장'],
  ['Lithops lesliei', '리톱스'],
  ['Conophytum bilobum', '코노피튬'],
  ['Portulacaria afra', '사철채송화'],
  ['Adenium obesum', '아데니움'],
  ['Euphorbia trigona', '대극'],
);

/** 허브·초화·채소 40종 */
export const HERB = entries(
  ['Ocimum basilicum', '바질'],
  ['Salvia rosmarinus', '로즈마리'],
  ['Thymus vulgaris', '타임'],
  ['Mentha spicata', '스피어민트'],
  ['Mentha piperita', '페퍼민트'],
  ['Mentha suaveolens', '애플민트'],
  ['Lavandula angustifolia', '라벤더'],
  ['Petroselinum crispum', '파슬리'],
  ['Lactuca sativa', '상추'],
  ['Solanum lycopersicum', '방울토마토'],
  ['Pelargonium × hortorum', '제라늄'],
  ['Pelargonium peltatum', '아이비제라늄'],
  ['Pelargonium graveolens', '로즈제라늄'],
  ['Petunia × atkinsiana', '페튜니아'],
  ['Viola × wittrockiana', '팬지'],
  ['Tagetes patula', '메리골드'],
  ['Chrysanthemum morifolium', '국화'],
  ['Capsicum annuum', '고추'],
  ['Fragaria × ananassa', '딸기'],
  ['Allium schoenoprasum', '차이브'],
  ['Coriandrum sativum', '고수'],
  ['Anethum graveolens', '딜'],
  ['Origanum vulgare', '오레가노'],
  ['Melissa officinalis', '레몬밤'],
  ['Salvia officinalis', '세이지'],
  ['Artemisia dracunculus', '타라곤'],
  ['Eruca vesicaria', '루꼴라'],
  ['Spinacia oleracea', '시금치'],
  ['Brassica rapa', '청경채'],
  ['Raphanus sativus', '무순'],
  ['Cymbopogon citratus', '레몬그라스'],
  ['Aloysia citrodora', '레몬버베나'],
  ['Stevia rebaudiana', '스테비아'],
  ['Impatiens walleriana', '임파첸스'],
  ['Begonia semperflorens', '사철베고니아'],
  ['Primula malacoides', '프리뮬러'],
  ['Antirrhinum majus', '금어초'],
  ['Matthiola incana', '스토크'],
  ['Calendula officinalis', '금잔화'],
  ['Catharanthus roseus', '일일초'],
);

/** 침엽 분재 20종 */
export const BONSAI_CONIFER = entries(
  ['Pinus thunbergii', '곰솔'],
  ['Pinus densiflora', '소나무'],
  ['Pinus parviflora', '섬잣나무'],
  ['Pinus pentaphylla', '오엽송'],
  ['Juniperus chinensis', '향나무'],
  ['Juniperus chinensis var. sargentii', '진백'],
  ['Juniperus rigida', '노간주나무'],
  ['Taxus cuspidata', '주목'],
  ['Cryptomeria japonica', '삼나무'],
  ['Taxodium distichum', '낙우송'],
  ['Metasequoia glyptostroboides', '메타세쿼이아'],
  ['Chamaecyparis obtusa', '편백'],
  ['Chamaecyparis pisifera', '화백'],
  ['Thuja orientalis', '측백나무'],
  ['Picea jezoensis', '가문비나무'],
  ['Abies koreana', '구상나무'],
  ['Larix kaempferi', '낙엽송'],
  ['Cedrus deodara', '히말라야시다'],
  ['Sciadopitys verticillata', '금송'],
  ['Torreya nucifera', '비자나무'],
);

/** 잡목·화목 분재 20종 */
export const BONSAI_DECIDUOUS = entries(
  ['Acer palmatum', '단풍나무'],
  ['Acer buergerianum', '중국단풍'],
  ['Acer japonicum', '당단풍'],
  ['Zelkova serrata', '느티나무'],
  ['Carpinus laxiflora', '서어나무'],
  ['Carpinus turczaninovii', '소사나무'],
  ['Chaenomeles japonica', '풀명자'],
  ['Rhododendron indicum', '영산홍'],
  ['Rhododendron yedoense', '산철쭉'],
  ['Rhododendron schlippenbachii', '철쭉'],
  ['Pseudocydonia sinensis', '모과나무'],
  ['Prunus mume var. bungo', '매실나무'],
  ['Crataegus pinnatifida', '산사나무'],
  ['Pyracantha angustifolia', '피라칸사'],
  ['Ginkgo biloba', '은행나무'],
  ['Celtis sinensis', '팽나무'],
  ['Ulmus parvifolia', '느릅나무'],
  ['Malus halliana', '꽃사과'],
  ['Wisteria floribunda', '등나무'],
  ['Berberis thunbergii', '매자나무'],
);

/** 300종 전체. 식물군별 구성은 SPEC 10.5 표와 같다 */
export const SEED_LIST: SeedEntry[] = [
  ...TROPICAL,
  ...TEMPERATE,
  ...SUCCULENT,
  ...HERB,
  ...BONSAI_CONIFER,
  ...BONSAI_DECIDUOUS,
];
